import { StyleSheet, Platform, SafeAreaView, StatusBar } from "react-native";
import { Dimensions } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#38B743",
    justifyContent: 'center',
  },
  container2: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 0,
    backgroundColor: "#38B743",
  },
  container3: {
    flex: 1,
    backgroundColor: "#38B743",
    justifyContent: "center",
    alignContent: "center",
    paddingBottom: 100,
    paddingTop: 50,
  },
  titleText: {
    fontFamily: "nunito-bold",
    fontSize: 18,
    color: "#333",
  },
  blockText: {
    //fontSize: 20,
    fontSize: Dimensions.get("window").height / 36,
    color: "white",
    fontFamily: "nunito-regular",
    textAlign: "left",
    //marginLeft: 10,
    marginLeft: Dimensions.get("window").height / 50,
  },
  blockText2: {
    //fontSize: 50,
    fontSize: Dimensions.get("window").height / 13,
    color: "#38B743",
    fontFamily: "nunito-bold",
    //marginVertical: 110,
    marginHorizontal: 20,
    marginVertical: Dimensions.get("window").height / 6.1,
  },
  blockText3: {
    //fontSize: 20,
    fontSize: Dimensions.get("window").height / 33,
    color: "#38B743",
    fontFamily: "nunito-bold",
    textAlign: "left",
    marginVertical: 0,
    //marginHorizontal: 45,
    //marginHorizontal: Dimensions.get('window').height / 13,
    textAlign: "center",
  },
  blockText4: {
    //fontSize: 50,
    fontSize: Dimensions.get("window").height / 13,
    color: "#38B743",
    fontFamily: "nunito-bold",
    textAlign: "left",
    //marginVertical: 90,
    marginVertical: Dimensions.get("window").height / 6,
    //marginHorizontal: 20,
    //marginHorizontal: Dimensions.get('window').height / 33,
    textAlign: "center",
  },
  blockText5: {
    fontSize: 25,
    fontSize: Dimensions.get("window").height / 26.5,
    color: "#38B743",
    fontFamily: "nunito-bold",
    textAlign: "left",
    marginVertical: 0,
    //marginHorizontal: 45,
    //marginHorizontal: Dimensions.get('window').height / 15,
    textAlign: "center",
  },
  blockHeader: {
    fontSize: 30,
    color: "white",
    fontFamily: "nunito-bold",
    textAlign: "center",
  },
  AndroidSafeArea: {
    flex: 1,
    backgroundColor: "white",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
});
